.TH docs 1 "21 July 2022" "version 1.0"

.SH NAME
docs - my own text editor

.SH SYNOPSIS
.B [-d] [-e]
.B [-f
.I filename
.B ]

.SH DESCRIPTION
.R Here is the
.B placeholder
.R for README.rst

.SH OPTIONS
.TP 
.R -d
directory for sitemap generator
.TP
.RI "-e  | " cleanup
ENVIRONMENT or cleanup file.
.TP
.RI -f " filename"
optional template file (
passed to yagg
).

.SH EXAMPLE
To create an example static generator/server

    #include <unistd.h>

    #ifndef EXP
    #define EXPAND_TAYLOR 0;
    #endif

    char * buf;
    size_t need;
    need = confstr('TEMPLATE_DIR', need, sizeof(buf))

    /*
    use `errno' or `fprintf' for logging
    */

    // int status = (char *) provide(...)

This is also what happens when running `make test'.

.SH RETURN VALUE
returns trapped signal by default. If
.IR cleanup " is provided, returns " EXIT_STATUS.

.SH FILES
You can pull your favorite pelican theme and set it as
.IR THEME " in the config file,"
or pass as argument to pelican invokation with
.B pelican \-t.
