

name: Pelican site CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: prepare
      run: |
        sudo apt update
        sudo apt install pelican bash
      
    - uses: actions/checkout@v2
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.5
      env:
        PELICAN_CONFIG_FILE: site/pelicanconf.py
        PELICAN_CONTENT_FOLDER: site/content
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
